language: node_js
node_js:
  # - "stable"
  - 10.16.1
  # - "7"
  # - "node"
cache: npm

install:
  - npm ci

script:
  - npm test
  - npm run build

# deploy:
#   provider: heroku
#   skip-cleanup: true